/// Dropbox transport. Stores a single .tachibk at the app's root. Auth
/// uses a Dropbox personal access token (generated by the user at
/// https://www.dropbox.com/developers/apps). Mihon does the same — the
/// token-refresh dance is left to the user.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:dio/dio.dart';

import 'sync_transport.dart';

class DropboxTransport extends SyncTransportFileStorage {
  DropboxTransport({required this.accessToken, required this.dio});

  final String accessToken;
  final Dio dio;

  static const String _remotePath = '/mohyeong-sync.tachibk';
  static const String _downloadUrl =
      'https://content.dropboxapi.com/2/files/download';
  static const String _uploadUrl =
      'https://content.dropboxapi.com/2/files/upload';

  @override
  Future<Uint8List?> pull() async {
    try {
      final response = await dio.post<List<int>>(
        _downloadUrl,
        options: Options(
          responseType: ResponseType.bytes,
          headers: {
            'Authorization': 'Bearer $accessToken',
            'Dropbox-API-Arg': jsonEncode({'path': _remotePath}),
          },
          // Dropbox uses 409 for "path/not_found"; treat as "no remote
          // file yet" (matches Mihon).
          validateStatus: (s) =>
              s != null && (s == 404 || s == 409 || (s >= 200 && s < 300)),
        ),
      );
      if (response.statusCode == 404 || response.statusCode == 409) return null;
      final bytes = response.data;
      if (bytes == null || bytes.isEmpty) return null;
      return Uint8List.fromList(bytes);
    } on DioException catch (e) {
      final code = e.response?.statusCode;
      if (code == 401) {
        throw SyncException('Dropbox auth failed — check your access token');
      }
      throw SyncException('Dropbox pull failed (HTTP ${code ?? '?'})');
    }
  }

  @override
  Future<void> push(Uint8List payload) async {
    try {
      await dio.post<void>(
        _uploadUrl,
        data: Stream.value(payload),
        options: Options(
          headers: {
            'Authorization': 'Bearer $accessToken',
            'Dropbox-API-Arg': jsonEncode({
              'path': _remotePath,
              'mode': 'overwrite',
              'mute': true,
            }),
            'Content-Type': 'application/octet-stream',
            'Content-Length': payload.length,
          },
          validateStatus: (s) => s != null && s >= 200 && s < 300,
        ),
      );
    } on DioException catch (e) {
      throw SyncException(
          'Dropbox push failed (HTTP ${e.response?.statusCode ?? '?'})');
    }
  }
}
