package eu.kanade.tachiyomi.data.sync

import eu.kanade.tachiyomi.network.NetworkHelper
import eu.kanade.tachiyomi.network.await
import okhttp3.MediaType.Companion.toMediaTypeOrNull
import okhttp3.Request
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.File

/**
 * Stores a single .tachibk file on Dropbox using a personal access token (generated by the user at
 * https://www.dropbox.com/developers/apps). Merge happens client-side via BackupRestorer.
 *
 * The access token is reused from the sync apiKey field.
 */
class DropboxTransport(
    private val accessToken: String,
    private val networkHelper: NetworkHelper,
) : SyncTransport.FileStorage {

    override suspend fun pull(): ByteArray? {
        val request = Request.Builder()
            .url(DOWNLOAD_URL)
            .header("Authorization", "Bearer $accessToken")
            .header("Dropbox-API-Arg", "{\"path\":\"$REMOTE_PATH\"}")
            .post(EMPTY_BODY)
            .build()

        val response = networkHelper.client.newCall(request).await()
        try {
            return when (response.code) {
                in 200..299 -> response.body.bytes().takeIf { it.isNotEmpty() }
                // Dropbox returns 409 for "path/not_found" — treat as no remote file yet.
                409, 404 -> null
                401 -> throw SyncException("Dropbox auth failed — check your access token")
                else -> throw SyncException("Dropbox pull failed (HTTP ${response.code})")
            }
        } finally {
            response.close()
        }
    }

    override suspend fun push(payload: File) {
        val request = Request.Builder()
            .url(UPLOAD_URL)
            .header("Authorization", "Bearer $accessToken")
            .header(
                "Dropbox-API-Arg",
                "{\"path\":\"$REMOTE_PATH\",\"mode\":\"overwrite\",\"mute\":true}",
            )
            .header("Content-Type", "application/octet-stream")
            .post(payload.asRequestBody(OCTET_STREAM))
            .build()

        val response = networkHelper.client.newCall(request).await()
        try {
            if (!response.isSuccessful) {
                throw SyncException("Dropbox push failed (HTTP ${response.code})")
            }
        } finally {
            response.close()
        }
    }

    companion object {
        private const val REMOTE_PATH = "/mohyeong-sync.tachibk"
        private const val DOWNLOAD_URL = "https://content.dropboxapi.com/2/files/download"
        private const val UPLOAD_URL = "https://content.dropboxapi.com/2/files/upload"
        private val OCTET_STREAM = "application/octet-stream".toMediaTypeOrNull()
        private val EMPTY_BODY = ByteArray(0).toRequestBody(null)
    }
}
